In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/amritachatterjee09/lead-scoring-dataset/Lead Scoring.csv
/kaggle/input/datasets/amritachatterjee09/lead-scoring-dataset/Leads Data Dictionary.xlsx
/kaggle/input/datasets/adityarathore117/lead-scoring/Lead Scoring.csv/Lead Scoring.csv
/kaggle/input/datasets/adityarathore117/lead-scoring/archive/Lead Scoring.csv
/kaggle/input/datasets/adityarathore117/lead-scoring/archive/Leads Data Dictionary.xlsx

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
import pandas as pd

df = pd.read_csv(
    "/kaggle/input/datasets/adityarathore117/lead-scoring/Lead Scoring.csv/Lead Scoring.csv"
)

In [4]:
df.head()

,Prospect ID,Lead Number,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,...,Get updates on DM Content,Lead Profile,City,Asymmetrique Activity Index,Asymmetrique Profile Index,Asymmetrique Activity Score,Asymmetrique Profile Score,I agree to pay the amount through cheque,A free copy of Mastering The Interview,Last Notable Activity
0,7927b2df-8bba-4d29-b9a2-b6e0beafe620,660737,API,Olark Chat,No,No,0,0.0,0,0.0,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Modified
1,2a272436-5132-4136-86fa-dcc88c88f482,660728,API,Organic Search,No,No,0,5.0,674,2.5,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Email Opened
2,8cc8c611-a219-4f35-ad23-fdfd2656bd8a,660727,Landing Page Submission,Direct Traffic,No,No,1,2.0,1532,2.0,...,No,Potential Lead,Mumbai,02.Medium,01.High,14.0,20.0,No,Yes,Email Opened
3,0cc2df48-7cf4-4e39-9de9-19797f9b38cc,660719,Landing Page Submission,Direct Traffic,No,No,0,1.0,305,1.0,...,No,Select,Mumbai,02.Medium,01.High,13.0,17.0,No,No,Modified
4,3256f628-e534-4826-9d63-4a8b88782852,660681,Landing Page Submission,Google,No,No,1,2.0,1428,1.0,...,No,Select,Mumbai,02.Medium,01.High,15.0,18.0,No,No,Modified

In [5]:
df.shape

(9240, 37)

In [6]:
# Basic Information
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns)

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

Shape: (9240, 37)

Columns:
Index(['Prospect ID', 'Lead Number', 'Lead Origin', 'Lead Source',
       'Do Not Email', 'Do Not Call', 'Converted', 'TotalVisits',
       'Total Time Spent on Website', 'Page Views Per Visit', 'Last Activity',
       'Country', 'Specialization', 'How did you hear about X Education',
       'What is your current occupation',
       'What matters most to you in choosing a course', 'Search', 'Magazine',
       'Newspaper Article', 'X Education Forums', 'Newspaper',
       'Digital Advertisement', 'Through Recommendations',
       'Receive More Updates About Our Courses', 'Tags', 'Lead Quality',
       'Update me on Supply Chain Content', 'Get updates on DM Content',
       'Lead Profile', 'City', 'Asymmetrique Activity Index',
       'Asymmetrique Profile Index', 'Asymmetrique Activity Score',
       'Asymmetrique Profile Score',
       'I agree to pay the amount through cheque',
       'A free copy of Mastering The Interview', 'Last Notable Activity'],
      dtype='object')

Data Types:
Prospect ID                                       object
Lead Number                                        int64
Lead Origin                                       object
Lead Source                                       object
Do Not Email                                      object
Do Not Call                                       object
Converted                                          int64
TotalVisits                                      float64
Total Time Spent on Website                        int64
Page Views Per Visit                             float64
Last Activity                                     object
Country                                           object
Specialization                                    object
How did you hear about X Education                object
What is your current occupation                   object
What matters most to you in choosing a course     object
Search                                            object
Magazine                                          object
Newspaper Article                                 object
X Education Forums                                object
Newspaper                                         object
Digital Advertisement                             object
Through Recommendations                           object
Receive More Updates About Our Courses            object
Tags                                              object
Lead Quality                                      object
Update me on Supply Chain Content                 object
Get updates on DM Content                         object
Lead Profile                                      object
City                                              object
Asymmetrique Activity Index                       object
Asymmetrique Profile Index                        object
Asymmetrique Activity Score                      float64
Asymmetrique Profile Score                       float64
I agree to pay the amount through cheque          object
A free copy of Mastering The Interview            object
Last Notable Activity                             object
dtype: object

Missing Values:
Prospect ID                                         0
Lead Number                                         0
Lead Origin                                         0
Lead Source                                        36
Do Not Email                                        0
Do Not Call                                         0
Converted                                           0
TotalVisits                                       137
Total Time Spent on Website                         0
Page Views Per Visit                              137
Last Activity                                     103
Country                                          2461
Specialization                                   1438
How did you hear about X Education               2207
What is your current occupation                  2690
What matters most to you in choosing a course    2709
Search                                              0
Magazine                                            0
Newspaper Article                                   0
X Education Forums                                  0
Newspaper                                           0
Digital Advertisement                               0
Through Recommendations                             0
Receive More Updates About Our Courses              0
Tags                                             3353
Lead Quality                                     4767
Update me on Supply Chain Content                   0
Get updates on DM Content                           0
Lead Profile                                     2709
City                                             1420
Asymmetrique Activity Index                      4218
Asymmetrique Profile Index                       4218
Asymmetrique Activity Score                      4218
Asymmetrique Profile Score                       4218
I agree to pay the amount through cheque            0
A free copy of Mastering The Interview              0
Last Notable Activity                               0
dtype: int64

In [7]:
# Shape of dataset
print("Number of Rows :", df.shape[0])
print("Number of Columns :", df.shape[1])

# First 5 rows
df.head()

Number of Rows : 9240
Number of Columns : 37

,Prospect ID,Lead Number,Lead Origin,Lead Source,Do Not Email,Do Not Call,Converted,TotalVisits,Total Time Spent on Website,Page Views Per Visit,...,Get updates on DM Content,Lead Profile,City,Asymmetrique Activity Index,Asymmetrique Profile Index,Asymmetrique Activity Score,Asymmetrique Profile Score,I agree to pay the amount through cheque,A free copy of Mastering The Interview,Last Notable Activity
0,7927b2df-8bba-4d29-b9a2-b6e0beafe620,660737,API,Olark Chat,No,No,0,0.0,0,0.0,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Modified
1,2a272436-5132-4136-86fa-dcc88c88f482,660728,API,Organic Search,No,No,0,5.0,674,2.5,...,No,Select,Select,02.Medium,02.Medium,15.0,15.0,No,No,Email Opened
2,8cc8c611-a219-4f35-ad23-fdfd2656bd8a,660727,Landing Page Submission,Direct Traffic,No,No,1,2.0,1532,2.0,...,No,Potential Lead,Mumbai,02.Medium,01.High,14.0,20.0,No,Yes,Email Opened
3,0cc2df48-7cf4-4e39-9de9-19797f9b38cc,660719,Landing Page Submission,Direct Traffic,No,No,0,1.0,305,1.0,...,No,Select,Mumbai,02.Medium,01.High,13.0,17.0,No,No,Modified
4,3256f628-e534-4826-9d63-4a8b88782852,660681,Landing Page Submission,Google,No,No,1,2.0,1428,1.0,...,No,Select,Mumbai,02.Medium,01.High,15.0,18.0,No,No,Modified

In [8]:
missing = pd.DataFrame({
    'Missing Values': df.isnull().sum(),
    'Percentage': round(df.isnull().mean()*100,2)
})

missing = missing.sort_values(by='Percentage', ascending=False)

missing

                                               Missing Values  Percentage
Lead Quality                                             4767       51.59
Asymmetrique Profile Index                               4218       45.65
Asymmetrique Activity Score                              4218       45.65
Asymmetrique Activity Index                              4218       45.65
Asymmetrique Profile Score                               4218       45.65
Tags                                                     3353       36.29
What matters most to you in choosing a course            2709       29.32
Lead Profile                                             2709       29.32
What is your current occupation                          2690       29.11
Country                                                  2461       26.63
How did you hear about X Education                       2207       23.89
Specialization                                           1438       15.56
City                                                     1420       15.37
Page Views Per Visit                                      137        1.48
TotalVisits                                               137        1.48
Last Activity                                             103        1.11
Lead Source                                                36        0.39
Do Not Email                                                0        0.00
Lead Origin                                                 0        0.00
Lead Number                                                 0        0.00
Prospect ID                                                 0        0.00
Newspaper                                                   0        0.00
X Education Forums                                          0        0.00
Newspaper Article                                           0        0.00
Magazine                                                    0        0.00
Search                                                      0        0.00
Total Time Spent on Website                                 0        0.00
Do Not Call                                                 0        0.00
Converted                                                   0        0.00
Get updates on DM Content                                   0        0.00
Update me on Supply Chain Content                           0        0.00
Through Recommendations                                     0        0.00
Receive More Updates About Our Courses                      0        0.00
Digital Advertisement                                       0        0.00
I agree to pay the amount through cheque                    0        0.00
A free copy of Mastering The Interview                      0        0.00
Last Notable Activity                                       0        0.00

We calculate the percentage of missing values because the decision to drop or impute a feature depends on the proportion of missing data, not just the count.

In [9]:
df.drop(['Prospect ID','Lead Number'], axis=1, inplace=True)

In [10]:
df.shape

(9240, 35)

In [11]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 1281

In [12]:
df.drop_duplicates(inplace=True)

In [13]:
for col in df.columns:
    print("="*60)
    print(col)
    print(df[col].value_counts().head())

============================================================
Lead Origin
Lead Origin
Landing Page Submission    4886
API                        2498
Lead Add Form               522
Lead Import                  52
Quick Add Form                1
Name: count, dtype: int64
============================================================
Lead Source
Lead Source
Google            2868
Direct Traffic    2543
Organic Search    1154
Olark Chat         673
Reference          410
Name: count, dtype: int64
============================================================
Do Not Email
Do Not Email
No     7263
Yes     696
Name: count, dtype: int64
============================================================
Do Not Call
Do Not Call
No     7957
Yes       2
Name: count, dtype: int64
============================================================
Converted
Converted
0    4776
1    3183
Name: count, dtype: int64
============================================================
TotalVisits
TotalVisits
2.0    1680
3.0    1306
4.0    1120
0.0     908
5.0     783
Name: count, dtype: int64
============================================================
Total Time Spent on Website
Total Time Spent on Website
0      912
60      19
75      18
74      18
127     18
Name: count, dtype: int64
============================================================
Page Views Per Visit
Page Views Per Visit
2.0    1795
3.0    1196
0.0     908
4.0     896
1.0     651
Name: count, dtype: int64
============================================================
Last Activity
Last Activity
Email Opened               3043
SMS Sent                   2427
Page Visited on Website     635
Olark Chat Conversation     474
Converted to Lead           428
Name: count, dtype: int64
============================================================
Country
Country
India                   6492
United States             69
United Arab Emirates      53
Singapore                 24
Saudi Arabia              21
Name: count, dtype: int64
============================================================
Specialization
Specialization
Select                       1491
Finance Management            957
Human Resource Management     831
Marketing Management          805
Operations Management         492
Name: count, dtype: int64
============================================================
How did you hear about X Education
How did you hear about X Education
Select                   4501
Online Search             808
Word Of Mouth             348
Student of SomeSchool     310
Other                     186
Name: count, dtype: int64
============================================================
What is your current occupation
What is your current occupation
Unemployed              5150
Working Professional     639
Student                  185
Other                     16
Housewife                 10
Name: count, dtype: int64
============================================================
What matters most to you in choosing a course
What matters most to you in choosing a course
Better Career Prospects      5986
Flexibility & Convenience       2
Other                           1
Name: count, dtype: int64
============================================================
Search
Search
No     7945
Yes      14
Name: count, dtype: int64
============================================================
Magazine
Magazine
No    7959
Name: count, dtype: int64
============================================================
Newspaper Article
Newspaper Article
No     7957
Yes       2
Name: count, dtype: int64
============================================================
X Education Forums
X Education Forums
No     7958
Yes       1
Name: count, dtype: int64
============================================================
Newspaper
Newspaper
No     7958
Yes       1
Name: count, dtype: int64
============================================================
Digital Advertisement
Digital Advertisement
No     7955
Yes       4
Name: count, dtype: int64
============================================================
Through Recommendations
Through Recommendations
No     7952
Yes       7
Name: count, dtype: int64
============================================================
Receive More Updates About Our Courses
Receive More Updates About Our Courses
No    7959
Name: count, dtype: int64
============================================================
Tags
Tags
Will revert after reading the email    1924
Ringing                                1143
Interested in other courses             473
Already a student                       407
Closed by Horizzon                      347
Name: count, dtype: int64
============================================================
Lead Quality
Lead Quality
Might be             1439
Not Sure             1073
High in Relevance     614
Low in Relevance      576
Worst                 552
Name: count, dtype: int64
============================================================
Update me on Supply Chain Content
Update me on Supply Chain Content
No    7959
Name: count, dtype: int64
============================================================
Get updates on DM Content
Get updates on DM Content
No    7959
Name: count, dtype: int64
============================================================
Lead Profile
Lead Profile
Select                   3751
Potential Lead           1509
Other Leads               484
Student of SomeSchool     201
Lateral Student            24
Name: count, dtype: int64
============================================================
City
City
Mumbai                         3209
Select                         1729
Thane & Outskirts               745
Other Cities                    685
Other Cities of Maharashtra     455
Name: count, dtype: int64
============================================================
Asymmetrique Activity Index
Asymmetrique Activity Index
02.Medium    3610
01.High       485
03.Low        349
Name: count, dtype: int64
============================================================
Asymmetrique Profile Index
Asymmetrique Profile Index
02.Medium    2254
01.High      2159
03.Low         31
Name: count, dtype: int64
============================================================
Asymmetrique Activity Score
Asymmetrique Activity Score
14.0    1687
15.0    1151
13.0     772
16.0     381
12.0     183
Name: count, dtype: int64
============================================================
Asymmetrique Profile Score
Asymmetrique Profile Score
15.0    1247
18.0    1069
16.0     585
17.0     556
20.0     306
Name: count, dtype: int64
============================================================
I agree to pay the amount through cheque
I agree to pay the amount through cheque
No    7959
Name: count, dtype: int64
============================================================
A free copy of Mastering The Interview
A free copy of Mastering The Interview
No     5071
Yes    2888
Name: count, dtype: int64
============================================================
Last Notable Activity
Last Notable Activity
Modified                   2847
Email Opened               2506
SMS Sent                   1887
Page Visited on Website     313
Email Link Clicked          142
Name: count, dtype: int64

In [14]:
constant_cols = []

for col in df.columns:
    if df[col].nunique() == 1:
        constant_cols.append(col)

print(constant_cols)

['Magazine', 'Receive More Updates About Our Courses', 'Update me on Supply Chain Content', 'Get updates on DM Content', 'I agree to pay the amount through cheque']

In [15]:
df.drop(columns=constant_cols, inplace=True)

In [16]:
round(df.isnull().mean()*100,2).sort_values(ascending=False)

Lead Quality                                     46.55
Asymmetrique Profile Score                       44.16
Asymmetrique Profile Index                       44.16
Asymmetrique Activity Index                      44.16
Asymmetrique Activity Score                      44.16
Tags                                             30.18
What matters most to you in choosing a course    24.75
Lead Profile                                     24.75
What is your current occupation                  24.51
How did you hear about X Education               18.44
Country                                          14.83
Specialization                                    8.78
City                                              8.57
TotalVisits                                       1.72
Page Views Per Visit                              1.72
Last Activity                                     1.29
Lead Source                                       0.41
Total Time Spent on Website                       0.00
Lead Origin                                       0.00
Do Not Email                                      0.00
Do Not Call                                       0.00
Converted                                         0.00
Digital Advertisement                             0.00
Through Recommendations                           0.00
X Education Forums                                0.00
Newspaper                                         0.00
Newspaper Article                                 0.00
Search                                            0.00
A free copy of Mastering The Interview            0.00
Last Notable Activity                             0.00
dtype: float64

In [17]:
drop_cols = [
'Lead Quality',
'Asymmetrique Activity Index',
'Asymmetrique Profile Index',
'Asymmetrique Activity Score',
'Asymmetrique Profile Score'
]

df.drop(columns=drop_cols, inplace=True)

In [18]:
df.shape

(7959, 25)

In [19]:
df.to_csv("lead_scoring_clean.csv",index=False)